### PR TITLE
Parse iOS SDK Version update to 1.6.5

### PR DESCRIPTION
**Pull request by fastrde**
Hi, I updated the iOS parse-library and the dependencies in plugin.xml.

### CODE REVIEW

**Comment by EricSimons** [comment]
+1 - currently breaking on iOS without this PR merged!

**Comment by fastrde** [comment]
updated to 1.7.1 cos XCode 6.3 is incompatible with 1.6.5

**Comment by ntrncic** [comment]
when i use this repo it works perfectly with IOS Thanks!

**Comment by benjie** [comment]
Thanks for the pull request but I no longer maintain this repository so I won't be merging - sorry! I advise all future visitors to check out fastrde's fork.

**Comment by vreemt** [comment]
after some digging, it appears https://github.com/grrrian/phonegap-parse-plugin is another fork but it seems to have current updates. thanks

**Comment by benjie** [comment]
Closing this pull request since I no longer maintain this repository.

**Pull request closed without merging**
